import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { ClerkProvider } from "@clerk/nextjs";
import QProvComp from "@/components/QProvComp";
import Footer from "@/components/Footer";
import TProvider from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Easy Kan Ban",
    description: "Generated by create next app",
    manifest: "/manifest.json",
    icons: {
        apple: "icon.png",
    },
    themeColor: "#0a0a0a",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={manrope.className}>
                <ClerkProvider>
                    <TProvider>
                        <QProvComp>
                            <Nav />
                            <div className="px-5 py-10 dark:bg-[#050505]">
                                {children}
                            </div>
                            <Footer />
                        </QProvComp>
                    </TProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
