// Generated by Xata Codegen 0.29.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Boards",
    columns: [
      { name: "name", type: "string" },
      { name: "user", type: "string" },
    ],
    revLinks: [{ column: "board", table: "Task" }],
  },
  {
    name: "Task",
    columns: [
      { name: "name", type: "string" },
      { name: "status", type: "string", notNull: true, defaultValue: "todo" },
      { name: "description", type: "text" },
      { name: "board", type: "link", link: { table: "Boards" } },
      { name: "importance", type: "link", link: { table: "Importance" } },
    ],
  },
  {
    name: "Importance",
    columns: [{ name: "Level", type: "string" }],
    revLinks: [{ column: "importance", table: "Task" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Boards = InferredTypes["Boards"];
export type BoardsRecord = Boards & XataRecord;

export type Task = InferredTypes["Task"];
export type TaskRecord = Task & XataRecord;

export type Importance = InferredTypes["Importance"];
export type ImportanceRecord = Importance & XataRecord;

export type DatabaseSchema = {
  Boards: BoardsRecord;
  Task: TaskRecord;
  Importance: ImportanceRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://ACBerny22-s-workspace-2m8h86.us-east-1.xata.sh/db/my-test-db",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
